version: "2.1"

services:
  db:
    image: postgres:14.4-bullseye
    ports:
      - 5432:5432
    env_file:
      - app.default.env
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    image: node:18.16.0-alpine3.17
    working_dir: "/backend"
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/backend/
    depends_on:
      - db
    command: ["npm", "start"]
    env_file:
      - app.default.env

  frontend:
    image: node:18.16.0-alpine3.17
    working_dir: "/frontend"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend/
    depends_on:
      - backend
    command: ["npm", "start"]
    env_file:
      - app.default.env
